import type { Community, Report, River, Site } from "./types";

export const SITES: Site[] = [
  // CRITICAL RISK
  {
    id: "GH-W-031",
    name: "Pra Basin Site",
    ha: 34.7,
    rivers: 2,
    region: "Western",
    risk: "CRITICAL",
    expanding: true,
    delta: 1.0,
    contamination: true,
  },
  {
    id: "GH-W-011",
    name: "Ankobra Headwaters",
    ha: 28.2,
    rivers: 3,
    region: "Western",
    risk: "CRITICAL",
    expanding: true,
    delta: 2.6,
    contamination: true,
  },
  {
    id: "GH-W-019",
    name: "Ofin River Site",
    ha: 19.8,
    rivers: 1,
    region: "Western",
    risk: "CRITICAL",
    expanding: false,
    delta: 0,
    contamination: true,
  },
  {
    id: "GH-AS-04",
    name: "Unverified Cluster 4",
    ha: 12.3,
    rivers: 1,
    region: "Ashanti",
    risk: "CRITICAL",
    expanding: false,
    delta: 0,
    contamination: true,
  },
  {
    id: "GH-CE-10",
    name: "Unverified Cluster 10",
    ha: 3.8,
    rivers: 1,
    region: "Central",
    risk: "CRITICAL",
    expanding: true,
    delta: 2.7,
    contamination: true,
  },
  {
    id: "GH-WN-20",
    name: "Unverified Cluster 20",
    ha: 8.5,
    rivers: 0,
    region: "Western North",
    risk: "CRITICAL",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-W-045",
    name: "Bonsa River Complex",
    ha: 27.1,
    rivers: 4,
    region: "Western",
    risk: "CRITICAL",
    expanding: true,
    delta: 3.2,
    contamination: true,
  },
  {
    id: "GH-AS-12",
    name: "Obuasi Periphery",
    ha: 22.6,
    rivers: 2,
    region: "Ashanti",
    risk: "CRITICAL",
    expanding: true,
    delta: 1.8,
    contamination: true,
  },

  // HIGH RISK
  {
    id: "GH-AS-01",
    name: "Bia Forest Site",
    ha: 41.3,
    rivers: 2,
    region: "Ashanti",
    risk: "HIGH",
    expanding: true,
    delta: 1.4,
    contamination: false,
  },
  {
    id: "GH-AS-07",
    name: "Subin Tributary Zone",
    ha: 12.4,
    rivers: 1,
    region: "Ashanti",
    risk: "HIGH",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-EA-03",
    name: "Birim North Clearing",
    ha: 22.1,
    rivers: 2,
    region: "Eastern",
    risk: "HIGH",
    expanding: true,
    delta: 1.6,
    contamination: false,
  },
  {
    id: "GH-AS-09",
    name: "Amansie West Cluster",
    ha: 15.2,
    rivers: 1,
    region: "Ashanti",
    risk: "HIGH",
    expanding: true,
    delta: 1.1,
    contamination: false,
  },
  {
    id: "GH-WN-01",
    name: "Unverified Cluster 1",
    ha: 15.1,
    rivers: 0,
    region: "Western North",
    risk: "HIGH",
    expanding: true,
    delta: 0.8,
    contamination: false,
  },
  {
    id: "GH-WE-02",
    name: "Unverified Cluster 2",
    ha: 13.1,
    rivers: 0,
    region: "Western",
    risk: "HIGH",
    expanding: true,
    delta: 1.4,
    contamination: false,
  },
  {
    id: "GH-CE-05",
    name: "Unverified Cluster 5",
    ha: 18.8,
    rivers: 0,
    region: "Central",
    risk: "HIGH",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-WN-19",
    name: "Unverified Cluster 19",
    ha: 6.0,
    rivers: 1,
    region: "Western North",
    risk: "HIGH",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-EA-08",
    name: "Akyem Mine Extension",
    ha: 31.4,
    rivers: 3,
    region: "Eastern",
    risk: "HIGH",
    expanding: true,
    delta: 2.1,
    contamination: true,
  },
  {
    id: "GH-BA-05",
    name: "Tano Basin Fringe",
    ha: 17.9,
    rivers: 2,
    region: "Bono",
    risk: "HIGH",
    expanding: true,
    delta: 0.9,
    contamination: false,
  },

  // MEDIUM RISK
  {
    id: "GH-BA-12",
    name: "Tano Headwaters",
    ha: 9.4,
    rivers: 2,
    region: "Bono",
    risk: "MEDIUM",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-UW-08",
    name: "Upper West Fringe",
    ha: 5.2,
    rivers: 0,
    region: "Upper West",
    risk: "MEDIUM",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-NR-07",
    name: "Gambaga Escarpment",
    ha: 11.6,
    rivers: 1,
    region: "Northern",
    risk: "MEDIUM",
    expanding: true,
    delta: 0.5,
    contamination: false,
  },
  {
    id: "GH-UE-03",
    name: "White Volta Buffer",
    ha: 8.3,
    rivers: 2,
    region: "Upper East",
    risk: "MEDIUM",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-OT-14",
    name: "Oti River Corridor",
    ha: 14.7,
    rivers: 3,
    region: "Oti",
    risk: "MEDIUM",
    expanding: true,
    delta: 1.2,
    contamination: false,
  },

  // LOW RISK
  {
    id: "GH-NR-15",
    name: "Northern Corridor Site",
    ha: 7.1,
    rivers: 1,
    region: "Northern",
    risk: "LOW",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-SV-02",
    name: "Savannah Woodland Zone",
    ha: 6.8,
    rivers: 0,
    region: "Savannah",
    risk: "LOW",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-UE-11",
    name: "Red Volta Protected Area",
    ha: 4.9,
    rivers: 1,
    region: "Upper East",
    risk: "LOW",
    expanding: false,
    delta: 0,
    contamination: false,
  },
  {
    id: "GH-BE-06",
    name: "Bolgatanga Periphery",
    ha: 5.5,
    rivers: 0,
    region: "Upper East",
    risk: "LOW",
    expanding: false,
    delta: 0,
    contamination: false,
  },
];

export const RIVERS: River[] = [
  {
    name: "Pra River",
    type: "Major",
    affectingSites: 7,
    km: 12.4,
    contaminated: true,
  },
  {
    name: "Ankobra River",
    type: "Major",
    affectingSites: 5,
    km: 8.2,
    contaminated: true,
  },
  {
    name: "Ofin River",
    type: "Major",
    affectingSites: 4,
    km: 5.1,
    contaminated: true,
  },
  {
    name: "Birim River",
    type: "Major",
    affectingSites: 6,
    km: 9.7,
    contaminated: true,
  },
  {
    name: "Tano River",
    type: "Major",
    affectingSites: 3,
    km: 4.8,
    contaminated: false,
  },
  {
    name: "Bonsa River",
    type: "Tributary",
    affectingSites: 4,
    km: 6.3,
    contaminated: true,
  },
  {
    name: "Subin River",
    type: "Tributary",
    affectingSites: 2,
    km: 3.1,
    contaminated: false,
  },
  {
    name: "White Volta",
    type: "Major",
    affectingSites: 2,
    km: 15.6,
    contaminated: false,
  },
  {
    name: "Oti River",
    type: "Major",
    affectingSites: 3,
    km: 7.9,
    contaminated: true,
  },
  {
    name: "Black Volta",
    type: "Major",
    affectingSites: 1,
    km: 2.4,
    contaminated: false,
  },
];

export const COMMUNITIES: Community[] = [
  { name: "Dunkwa-on-Offin", population: 12_400, exposure: 88 },
  { name: "Prestea", population: 9800, exposure: 65 },
  { name: "Tarkwa Suburbs", population: 15_200, exposure: 42 },
  { name: "Obuasi Town", population: 28_500, exposure: 91 },
  { name: "Akyem Oda", population: 7600, exposure: 73 },
  { name: "Bibiani", population: 11_200, exposure: 58 },
  { name: "Bogoso", population: 8900, exposure: 82 },
  { name: "Akropong", population: 14_500, exposure: 47 },
  { name: "Kibi", population: 6700, exposure: 39 },
  { name: "Wassa Akropong", population: 9800, exposure: 68 },
];

export const REPORTS: Report[] = [
  {
    title: "Weekly Situation Report — W18",
    date: "MAY 01, 2026",
    type: "System Generated",
  },
  {
    title: "Site Deep Dive: GH-W-031",
    date: "APR 28, 2026",
    type: "Manual Export",
  },
  {
    title: "Weekly Situation Report — W17",
    date: "APR 24, 2026",
    type: "System Generated",
  },
  {
    title: "River Contamination Assessment Q2",
    date: "APR 15, 2026",
    type: "System Generated",
  },
  {
    title: "High Risk Sites Monitoring Report",
    date: "APR 10, 2026",
    type: "Manual Export",
  },
  {
    title: "Community Exposure Analysis — April",
    date: "APR 05, 2026",
    type: "System Generated",
  },
  {
    title: "Illegal Mining Hotspots Update",
    date: "MAR 28, 2026",
    type: "Manual Export",
  },
  {
    title: "Weekly Situation Report — W16",
    date: "MAR 20, 2026",
    type: "System Generated",
  },
];
