export const ENV_CONSTANTS = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  FRONTEND_URL: 'FRONTEND_URL',
  DATABASE_URL: 'DATABASE_URL',
  DB_SSL: 'DB_SSL',
  PYTHON_ENGINE_URL: 'PYTHON_ENGINE_URL',
  ENABLE_SWAGGER: 'ENABLE_SWAGGER',
} as const;
